backend:
  name: github
  repo: cnk/website
  open_authoring: true
media_folder: "assets/images/projects" # Media files will be stored in the repo in this directory
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Github Project ID", name: "identification", widget: "hidden", default: ""}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Card Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Hero Image", name: "image-hero", widget: "image", required: false}
      - {label: "Hero Alt Text", name: "alt-hero", widget: "string", required: false}
      - label: "Leadership"
        name: "leadership"
        widget: "list"
        required: false
        fields:
          - {label: "Full Name", name: "name", widget: "string"}
          - {label: "Role", name: "role", widget: "string", required: false}
          - {label: "Image", name: "picture", widget: "string", hint: "Avatar url, e.g. https://avatars.githubusercontent.com/ExperimentsInHonesty"}
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Slack URL", name: "slack", widget: "string", required: false}
              - {label: "GitHub Profile URL", name: "github", widget: "string", required: false}
      - label: "Project Links"
        name: "links"
        widget: "list"
        required: false
        hint: "Please provide links to your GitHub project, Wiki, Slack channel, Site, Test Site, etc."
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
      - {label: "Looking", name: "looking", widget: "list", required: false}
      - {label: "Location", name: "location", widget: "string", required: false, hint: "One or more of Downtown LA, Santa Monica, South LA, Remote"}
      - {label: "Partner", name: "partner", widget: "string", required: false}
      - {label: "Status", name: "status", widget: "string", hint: "Options: Active, Rebooting, On Hold, Completed"}



